#!/bin/bash
# note that this repository has to have had
#   git submodule init
# called in it. This is because the copy to dash-sample-apps takes the contents
# of the submodules and deletes the .gitmodules file, so dash-sample-apps just
# thinks these are subfolders.

[ -z $DASH_SAMPLE_APPS_DIR ] && DASH_SAMPLE_APPS_DIR="$HOME/development/dash-sample-apps"

repo_name="$(basename $(pwd))"

copy_to_dir="$DASH_SAMPLE_APPS_DIR/apps/$repo_name"

rm -rf "$copy_to_dir"
cp -rf "../$repo_name" "$copy_to_dir" \
    && (echo "Copied to $copy_to_dir" && \
        rm -rf \
            "$copy_to_dir/.git" \
            "$copy_to_dir/.gitmodules" \
            "$copy_to_dir/plotly-common/.git") \
    || echo "Copy to $copy_to_dir failed."
