apiVersion: v1
kind: Service
metadata:
  labels:
    name: omnisci-service
  name: omnisci-service
spec:
  ports:
  - protocol: TCP
    port: 6274
    targetPort: 6274
  selector:
    name: omnisci-node
  type: LoadBalancer
