library(data.table)

regions <- data.table(
  Country = c(
    # 23 north american countries:
    "Cuba",
    "Dominican Republic",
    "El Salvador",
    "Guadeloupe",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Martinique",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Puerto Rico",
    "Saint Barthelemy",
    "USA",
    "Candada",
    "USVI",
    "Dominica",
    "Trinidad and Tobago",
    "Belize",
    "Grenada",
    "Costa Rica",
    "Bermuda",
    # 13 south american countries
    "Brazil",
    "Colombia",
    "Ecuador",
    "French Guiana",
    "Peru",
    "Suriname",
    "Venezuela",
    "Puerto Rico",
    "Argentina",
    "Bolivia",
    "Paraguay",
    "Chile",
    "Aruba",
    # 10 South Asia counties,
    "Singapore",
    "Vietnam",
    "Malaysia",
    "Philippines",
    "Thailand",
    "Myanmar",
    "Cambodia",
    "Indonesia",
    "Brunei",
    "Laos",
    # 18 Oceania counties
    "American Samoa",
    "Fiji",
    "French Polynesia",
    "Tonga",
    "Australia",
    "Micronesia",
    "New Caledonia",
    "Marshall Islands",
    "Guam",
    "Papua New Guinea",
    "Solomon Islands",
    "Cook Islands",
    "Samoa",
    "Nauru",
    "Palau",
    "Vanuatu",
    "Niue",
    "New Zealand",
    # China
    "China",
    # Japan Korea
    "Japan",
    # 53 African countries
    "Guinea",
    "Liberia",
    "Sierra Leone",
    "Côte D'Ivoire",
    "Angola",
    "Comoros",
    "Madagascar",
    "Eritrea",
    "Somalia",
    "Djibouti",
    "Burkina Faso",
    "Ghana",
    "Tanzenia",
    "Mozambique",
    "Senegal",
    "Togo",
    "Sudan",
    "Gambia",
    "Nigeria",
    "Mali",
    "Senegal",
    "Cote D'Ivoire",
    "Burkina Faso",
    "Seychelles",
    "Somalia",
    "Ghana",
    "Tanzania",
    "Mozambique",
    "Djibouti",
    "Madagascar",
    "Comoros",
    "Togo",
    "Angola",
    "Eritria",
    "Guinea",
    "Sierra Leone",
    "Liberia",
    "Tunisia",
    "Cameroon",
    "South Africa",
    "Congo Republic",
    "Congo DRC",
    "Algeria",
    "Morocco",
    "Zambia",
    "Kenya",
    "Uganda",
    "Egypt",
    "Ethiopia",
    "Niger",
    "Mayotte",
    "Rwanda",
    "Gabon",
    # 20 European Countries:
    "France",
    "Germany",
    "Italy",
    "United Kingdom",
    "Netherlands",
    "Spain",
    "Portugal",
    "Ireland",
    "Slovakia",
    "Romania",
    "Sweden",
    "Norway",
    "Slovenia",
    "Denmark",
    "Iceland",
    "Ukraine",
    "Czech Republic",
    "Albania",
    "Greece",
    "Latvia"
  ),
  region = c(
    rep("North America", 23), 
    rep("South America", 13),
    rep("South Asia", 10),
    rep("Oceania", 18),
    "China",
    "Japan Korea",
    rep("Africa", 53),
    rep("Europe", 20)
  )
)

fwrite(unique(regions), file = "regions.csv")

