
appName <- Sys.getenv("DASH_APP_NAME")
if (appName != ""){
  pathPrefix <- sprintf("/%s/", appName)
  
  Sys.setenv(DASH_ROUTES_PATHNAME_PREFIX = pathPrefix,
             DASH_REQUESTS_PATHNAME_PREFIX = pathPrefix)
  
  setwd(sprintf("/app/apps/%s", appName))
}

library(dash)
library(dashCoreComponents)
library(dashHtmlComponents)
library(plotly)


##################### GLOBAL OBJECTS ###############################################

addButton <- htmlButton('Add', id = 'add-button')

delButton <- htmlButton('Delete', id = 'del-button')

titleInput <- dccInput(
  placeholder = 'Enter New Title Here',
  type = 'text',
  value = ''
)

trace <- dccInput(
  placeholder = 'Trace #',
  type = 'text',
  value = ''
)

trace1234 <- dccInput(
  placeholder = '1,2,3,4',
  type = 'text',
  value = ''
)

trace3333 <- dccInput(
  placeholder = '3,3,3,3',
  type = 'text',
  value = ''
)

styleOptions <-list(
  list(label = "0", value = "0"),
  list(label = "circle", value = "circle"),
  list(label = "100", value = "100"),
  list(label = "circle-open", value = "circle-open"),
  list(label = "200", value = "200"),
  list(label = "circle-dot", value = "circle-dot"),
  list(label = "300", value = "300"),
  list(label = "circle-open-dot", value = "circle-open-dot"),
  list(label = "1", value = "1"),
  list(label = "square", value = "square"),
  list(label = "101", value = "101"),
  list(label = "square-open", value = "square-open"),
  list(label = "201", value = '201'),
  list(label = "square-dot", value = "square-dot"),
  list(label = "301", value = "301"),
  list(label = "square-open-dot", value = "square-open-dot"),
  list(label = "2", value = "2"),
  list(label = "diamond", value = "diamond"),
  list(label = "102", value = "102"),
  list(label = "diamond-open", value = "diamond-dot"),
  list(label = "202", value = "202"),
  list(label = "diamond-dot", value = "diamond-dot"),
  list(label = "302", value = "302"),
  list(label = "diamond-open-dot", value = "diamond-open-dot"),
  list(label = "3", value = "3"),
  list(label = "cross", value = "cross"),
  list(label = "103", value = "103"),
  list(label = "cross-open", value = "cross-open"),
  list(label = "203", value = "203"),
  list(label = "cross-dot", value = "cross-dot"),
  list(label = "303", value = "303"),
  list(label = "cross-open-dot", value = "cross-open-dot"),
  list(label = "x", value = "x"),
  list(label = "104", value = "104"),
  list(label = "x-open", value = "x-open"),
  list(label = "204", value = "204"),
  list(label = "x-dot", value = "x-dot"),
  list(label = "304", value = "304"),
  list(label = "x-open-dot", value = "x-open-dot"),
  list(label = "5", value = "5"),
  list(label = "triangle-up", value = "triangle-up"),
  list(label = "105", value = "105"),
  list(label = "triangle-up-open", value = "triangle-up-open"),
  list(label = "205", value = "205"),
  list(label = "triangle-up-dot", value = "triangle-up-dot"),
  list(label = "305", value = "305"),
  list(label = "triangle-up-open-dot", value = "triangle-up-open-dot"),
  list(label = "6", value = "6"),
  list(label = "triangle-down", value = "triangle-down"),
  list(label = "106", value = "106"),
  list(label = "triangle-down-open", value = "triangle-down-open"),
  list(label = "206", value = "206"),
  list(label = "triangle-down-dot", value = "triangle-down-dot"),
  list(label = "306", value = "306"),
  list(label = "triangle-down-open-dot", value = "triangle-down-open-dot"),
  list(label = "7", value = "7"),
  list(label = "triangle-left", value = "triangle-left"),
  list(label = "107", value = "107"),
  list(label = "triangle-left-open", value = "triangle-left-open"),
  list(label = "307", value = "307"),
  list(label = "triangle-left-open-dot", value = "triangle-left-open-dot"),
  list(label = "8", value = "8"),
  list(label = "triangle-right", value = "triangle-right"),
  list(label = "108", value = "108"),
  list(label = "triangle-right-open", value = "triangle-right-open"),
  list(label = "208", value = "208"),
  list(label = "triangle-right-dot", value = "triangle-right-dot"),
  list(label = "308", value = "308"),
  list(label = "triangle-right-open-dot", value = "triangle-right-open-dot"), 
  list(label = "9", value = "9"),
  list(label = "triangle-ne", value = "triangle-ne"),
  list(label = "109", value = "109"),
  list(label = "triangle-ne-open", value = "triangle-ne-dot"),
  list(label = "209", value = "209"),
  list(label = "triangle-ne-dot", value = "triangle-ne-dot"),
  list(label = "309", value = "309"),
  list(label = "triangle-ne-open-dot", value = "triangle-ne-open-dot"),
  list(label = "10", value = "10"),
  list(label = "triangle-se", value = "triangle-se"),
  list(label = "110", value = "110"),
  list(label = "triangle-se-open", value = "triangle-se-open"),
  list(label = "210", value = "210"),
  list(label = "triangle-se-dot", value = "triangle-se-dot"),
  list(label = "310", value = "310"),
  list(label = "triangle-se-open-dot", value = "triangle-se-open-dot"),
  list(label = "11", value = "11"),
  list(label = "triangle-sw", value = "triangle-sw"),
  list(label = "111", value = "111"),
  list(label = "triangle-sw-open", value = "triangle-sw-open"),
  list(label = "211", value = "211"),
  list(label = "triangle-sw-dot", value = "triangle-sw-dot"),
  list(label = "311", value = "311"),
  list(label = "triangle-sw-open-dot", value = "triangle-sw-open-dot"),
  list(label = "12", value = "12"),
  list(label = "triangle-nw", value = "triangle-nw)"),
  list(label = "112", value = "112"),
  list(label = "triangle-nw-open", value = "triangle-nw-open"),
  list(label = "212", value = "212"),
  list(label = "triangle-nw-dot", value = "triangle-nw-dot"),
  list(label = "312", value = "312"),
  list(label = "triangle-nw-open-dot", value = "triangle-new-open-dot"),
  list(label = "13", value = "13"),
  list(label = "pentagon", value = "pentagon"),
  list(label = "113", value = "113"),
  list(label = "pentagon-open", value = "pentagon-open"),
  list(label = "213", value = "213"),
  list(label = "pentagon-dot", value = "pentagon-dot"),
  list(label = "313", value = "313"),
  list(label = "pentagon-open-dot", value = "pentagon-open-dot"),
  list(label = "14", value = "14"), 
  list(label = "hexagon", value = "hexagon"),
  list(label = "114", value = "114"),
  list(label = "hexagon-open", value = "214"),
  list(label = "214", value = "214"),
  list(label = "hexagon-dot", value = "hexagon-dot"),
  list(label = "314", value = "314"),
  list(label = "hexagon-open-dot", value = "hexagon-open-dot"),
  list(label = "15", value = "15"),
  list(label = "hexagon2", value = "hexagon2"),
  list(label = "115", value = "115"),
  list(label = "hexagon2-open", value = "hexagon2-open"),
  list(label = "215", value = "215"),
  list(label = "hexagon2-dot", value = "hexagon2-dot"),
  list(label = "315", value = "315"),
  list(label = "hexagon2-open-dot", value = "hexagon2-open-dot"),
  list(label = "16", value = "16"),
  list(label = "octagon", value = "octagon"),
  list(label = "116", value = "116"),
  list(label = "octagon-open", value = "octagon-open"),
  list(label = "216", value = "216"),
  list(label = "octagon-dot", value = "octagon-dot"),
  list(label = "316", value = "316"),
  list(label = "octagon-open-dot", value = "octagon-open-dot"),
  list(label = "17", value = "17"),
  list(label = "star", value = "star"),
  list(label = "117", value = "117"),
  list(label = "217", value = "217"),
  list(label = "star-dot", value = "star-dot"),
  list(label = "317", value = "317"),
  list(label = "star-open-dot", value = "star-open-dot"),
  list(label = "18", value = "18"),
  list(label = "hexagram", value = "hexgram"),
  list(label = "118", value = "118"),
  list(label = "hexagram-open", value = "hexagram-open"),
  list(label = "218", value = "218"),
  list(label = "hexagram-dot", value = "hexagram-dot"),
  list(label = "318", value = "318"),
  list(label = "hexagram-open-dot", value = "hexagram-open-dot"),
  list(label = "19", value = "19"),
  list(label = "star-triangle-up", value = "star-triangle-up"),
  list(label = "119", value = "119"),
  list(label = "star-triangle-up-dot-open"),
  list(label = "219", value = "219"),
  list(label = "star-triangle-up-dot"),
  list(label = "319", value = "319"),
  list(label = "star-triangle-open-dot", value = "star-triangle-open-dot"),
  list(label = "20", value = "20"),
  list(label = "star-triangle-down-open", value = "star-triangle-down-open"),
  list(label = "120", value = "120"),
  list(label = "star-triangle-dot-open", value = "star-triangle-dot-open"),
  list(label = "220", value = "220"),
  list(label = "star-triangle-down-dot" , value = "star-triangle-down-dot"),
  list(label = "320", value = "320"),
  list(label = "star-triangle-down-open-dot", value = "star-triangle-down-open-dot"),
  list(label = "21", value = "21"),
  list(label = "star-square", value = "star-square"),
  list(label = "121", value = "121"),
  list(label = "star-square-open", value = "star-square-open"),
  list(label = "221", value = "221"),
  list(label = "star-square-dot", value = "star-square-dot"),
  list(label = "321", value = "321"),
  list(label = "star-square-open-dot", value = "star-square-open-dot"),
  list(label = "22", value = "22"),
  list(label = "star-diamond", value = "star-diamond"),
  list(label = "122", value = "122"),
  list(label = "star-diamond-open", value = "star-diamond-open"),
  list(label = "222", value = "322"),
  list(label = "star-diamond-dot", value = "star-diamond-dot"),
  list(label = "322", value = "322"),
  list(label = "star-diamond-open-dot", value = "star-diamond-open-dot"),
  list(label = "23", value = "23"),
  list(label = "diamond-tall", value = "diamond-tall"),
  list(label = "123", value = "123"),
  list(label = "diamond-tall-open", value = "diamond-tall-open"),
  list(label = "223", value = "223"),
  list(label = "diamond-tall-dot", value = "diamond-tall-dot"),
  list(label = "323", value = "323"),
  list(label = "diamond-tall-open-dot", value = "diamond-tall-open-dot",
  list(label = "24", value = "24"),
  list(label = "diamond-wide", value = "diamond-wide"),
  list(label = "124", value = "124"),
  list(label = "diamond-wide-open", value = "diamond-wide-open"),
  list(label = "224", value = "224"),
  list(label = "diamond-wide-dot", value = "diamond-wide-dot"),
  list(label = "324", value = "324"),
  list(label = "diamond-wide-open-dot", value = "diamond-wide-open-dot"),
  list(label = "25", value = "25"),
  list(label = "hourglass", value = "hourglass"),
  list(label = "125", value = "125"),
  list(label = "hourglass-open", value = "hourglass-open"),
  list(label = "26", value = "26"),
  list(label = "bowtie", value = "bowtie"),
  list(label = "126", value = "126"),
  list(label = "bowtie-open", value = "bowtie-open"),
  list(label = "27", value = "27"),
  list(label = "circle-cross", value = "circle-cross"),
  list(label = "127", value = "127"),
  list(label = "circle-cross-open", value = "circle-cross-open"),
  list(label = "28", value = "28"),
  list(label = "circle-x", value = "circle-x"),
  list(label = "128", value = "128"),
  list(label = "circle-x-open", value = "circle-x-open"),
  list(label = "29", value = "29"),
  list(label = "square-cross", value = "square-cross"),
  list(label = "129", value = "129"),
  list(label = "square-cross-open", value = "square-cross-open"),
  list(label = "30", value = "30"),
  list(label = "square-x", value = "square-x"),
  list(label = "130", value = "130"),
  list(label = "square-x-open", value = "square-x-open"),
  list(label = "31", value = "31"),
  list(label = "diamond-cross", value = "diamond-cross"),
  list(label = "131", value = "131"),
  list(label = "diamond-cross-open", value = "diamond-cross-open"),
  list(label = "32", value = "32"),
  list(label = "diamond-x", value = "diamond-x"),
  list(label = "132", value = "132"),
  list(label = "diamond-x-open", value = "diamond-x-open"),
  list(label = "33", value = "33"),
  list(label = "cross-thin", value = "cross-thin"),
  list(label = "133", value = "133"),
  list(label = "cross-thin-open", value = "cross-thin-open"),
  list(label = "34", value = "34"),
  list(label = "x-thin", value = "x-thin"),
  list(label = "134", value = "134"),
  list(label = "x-thin-open", value = "x-thin-open"),
  list(label = "35", value = "35"),
  list(label = "asterisk", value = "asterisk"),
  list(label = "135", value = "135"),
  list(label = "asterisk-open", value = "asterisk-open"),
  list(label = "36", value = "36"),
  list(label = "hash", value = "hash"), 
  list(label = "136", value = "136"),
  list(label = "hash-open", value = "hash-open"),
  list(label = "236", value = "236"),
  list(label = "hash-dot", value = "hash-dot"),
  list(label = "336", value = "336"),
  list(label = "hash-open-dot", value = "hash-open-dot"),
  list(label = "137", value = "137"),
  list(label = "y-up-open", value = "y-up-open"),
  list(label = "38", value = "38"),
  list(label = "y-down", value = "y-down"),
  list(label = "138", value = "138"),
  list(label = "y-down-open", value = "y-down-open"),
  list(label = "39", value = "39"),
  list(label = "y-left", value = "y-left"),
  list(label = "139", value = "139"),
  list(label = "y-left-open", value = "y-left-open"),
  list(label = "40", value = "40"),
  list(label = "y-right", value = "y-right"),
  list(label = "140", value = "140"),
  list(label = "y-right-open", value = "y-right-open"),
  list(label = "41", value = "41"),
  list(label = "line-ew", value = "line-ew"),
  list(label = "141", value = "141"),
  list(label = "line-ew-open", value = "line-ew-open"),
  list(label = "42", value = "42"),
  list(label = "line-ns", value = "line-ns"),
  list(label = "142", value = "142"),
  list(label = "line-ns-open", value = "line-ns-open"),
  list(label = "43", value = "43"),
  list(label = "line-ne", value = "line-ne"),
  list(label = "143", value = "143"),
  list(label = "line-ne-open", value = "line-ne-open"),
  list(label = "44", value = "44"),
  list(label = "line-nw", value = "line-nw"),
  list(label = "144", value = "144"),
  list(label = "line-nw-open", value = "line-nw-open"),
)

#############################CREATE LAYOUT VARIABLES################################

plotlyLogo <- htmlA(
  list(
    htmlImg(src = "assets/dash-logo-new.png",
            className = "logo")),
  href = "https://dashr-docs.herokuapp.com/")

styleDropDown <- dccDropdown(id = "style-dropdown",
                             options = styleOptions,
                             multi = TRUE,
                             value = "circle")

####################################################################################################

if (appName != "") {
  app$run_server(host = "0.0.0.0", port = Sys.getenv('PORT', 8050)) 
} else {
  app$run_server()
}
